name: Content Sync

on:
  push:
    branches:
      - master
    paths:
      - 'project_*/*.html'
      - '.github/workflows/content-sync.yml'
      - '.github/scripts/**'

jobs:
  sync:
    runs-on: arc-runners-small
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install supabase
          
      - name: Sync stage content to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python .github/scripts/sync_content.py