name: Delete Draft Projects

on:
  pull_request:
    types: [closed]

jobs:
  delete-drafts:
    name: Delete Draft Projects
    runs-on: arc-runners-small
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (Python)
        run: |
          python -m pip install --upgrade pip
          pip install supabase

      - name: Delete draft projects
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PR_NUMBER: ${{ github.event.number }}
        run: python .github/scripts/delete_drafts.py
